[tool.poetry]
name = "king"
version = "0.1.3"
description = ""
authors = ["Bryan Hann <nobody@nowhere>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
touch = 'king.midas:touch'
midas = 'king.midas:mtouch'
